### ISSUE TITLE
Desired cleanups

### ISSUE THREAD

**Issue by jonnor** [flowhub/the-graph#314]
Right now the code has a couple of warts

* Business logic intermixed with rendering
* State is kept in many different places in 
* No separation of state which affects the underlying graph, and what just affects the presentation/view
* Pulls in all of NoFlo (incl the FBP runtime). Right now quite fat, and confusing 

Also, we need to get rid of Polymer, see #222

## TODO

* [ ] Split out the Graph things from NoFlo, and use that instead of NoFlo.
* [ ] Get rid of `the-graph-editor` versus `the-graph` distinction. Nothing uses `the-graph`.
* [ ] Get rid of `the-graph-nav` versus `the-graph-thumb` distinction. Nothing uses `the-graph-thumb`.
* [ ] Make `the-graph-editor` usable without any Polymer wrapping
* [ ] Make `the-graph-nav` usable without any Polymer wrapping
* [ ] Move the Polymer elements over to noflo-ui, remove the dependency

## Loose guidelines

* Add tests before rewriting. #313
* Move logic from Polymer .HTML components down into .JS files.
* Introduce a dedicated "ViewState" for keeping track of state which affects View.
Pan/zoom/scroll, selection
* Introduce a dedicated "State". Contains primarily the NoFlo/FBP graph, but also components
* Move the library/component code into part of State

**Comment by jonnor** [comment]
An open question is how to do gestures without Polymer.

**Comment by forresto** [comment]
noflo-ui does use the-graph-thumb: https://github.com/noflo/noflo-ui/blob/1ddb399017ecb2da99c4033f9ecfc1e4deedc9b5/elements/noflo-main.html#L199

**Comment by forresto** [comment]
the-graph-editor / the-graph was supposed to be like the-graph-nav / the-graph-thumb, with navigation separated from rendering. Good idea to make those separate (React) components.

**Comment by jonnor** [comment]
Fair points. Keeping interactivity away from rendering is good. Updated description.

**Comment by forresto** [comment]
Reason for including noflo originally was to listen to changes from elsewhere (p2p) -- https://github.com/flowhub/the-graph/blob/c3b6a15eb41d079c625e07359d212c9ebb84f0f4/the-graph/the-graph-graph.js#L102-L116

**Comment by jonnor** [comment]
Yes, and that is still legit. Its just that this functionality should move outside of NoFlo so it can be shared more nicely.

**Comment by jonnor** [comment]
the-graph 0.5.x no longer depends on NoFlo, using new fbp-graph librayr instead #316

**Comment by jonnor** [comment]
#320 has a lot of cleanups that reduces dependency on Polymer elements a lot.

**Comment by jonnor** [comment]
Things that still are a bit unclear:

* component library handling
* event handling
* selection (nodes, edges) handling
